### ISSUE TITLE
Regression: Shop Empire 2 - Error dispatching event "enterSomeFrame"

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#22997]
### Describe the bug

After entering my name, I want to start the game, but there is just a white screen. Looks like another regression started with https://github.com/ruffle-rs/ruffle/pull/22408
```
ERROR core/src/avm2.rs:688 Error dispatching event "enterSomeFrame": TypeError: Error #1009: Cannot access a property or method of a null object reference.
at ShopEmpire2_fla::MainProgram_64/checkFrame()
at flash.events::EventDispatcher/dispatchEventInternal()
at flash.events::EventDispatcher/dispatchEvent()
at ShopEmpire2_fla::MainProgram_64/frame2()
```

### Expected behavior

Run the first level

### Content Location

PLAY Online - https://www.gameflare.com/online-game/shop-empire-2/
SWF URL - https://data.gameflare.com/games/2892/Mtia6vHMFbAR6E.swf

SWF Version: 9

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
This is probably the same issue as #22677
