### ISSUE TITLE
Gaia Aquarium game black screen with Nightly 2024-06-22 build

### ISSUE THREAD

**Issue by lanzer-gaia** [ruffle-rs/ruffle#16909]
### Describe the bug

Starting from nightly build from 06/22, our Aquarium game could no longer start.

Console log showed numerous errors that weren't present in earlier versions:
`ruffle_web-wasm_extensions.js:1195 ERROR core/src/display_object/movie_clip.rs:4371 Got AVM2 error ReferenceError: Error #1065: Variable _SWFLoaderStyle__embed_css_Assets_swf___brokenImage_589047538 is not defined. when attempting to assign symbol class _SWFLoaderStyle__embed_css_Assets_swf___brokenImage_589047538
ruffle_web-wasm_extensions.js:1195 ERROR core/src/display_object/movie_clip.rs:4371 Got AVM2 error ReferenceError: Error #1065: Variable EditorAssets_QUEST_BUTTON_ACCEPT is not defined. when attempting to assign symbol class com.gaiaonline.aquarium.model::EditorAssets_QUEST_BUTTON_ACCEPT
ruffle_web-wasm_extensions.js:1195 ERROR core/src/display_object/movie_clip.rs:4371 Got AVM2 error ReferenceError: Error #1065: Variable EditorAssets_QUEST_BUTTON_ACTIVE_ROLLOVER is not defined. when attempting to assign symbol class com.gaiaonline.aquarium.model::EditorAssets_QUEST_BUTTON_ACTIVE_ROLLOVER
ruffle_web-wasm_extensions.js:1195 ERROR core/src/display_object/movie_clip.rs:4371 Got AVM2 error ReferenceError: Error #1065: Variable InventoryPanel_talkToNPC is not defined. when attempting to assign symbol class com.gaiaonline.aquarium.view::InventoryPanel_talkToNPC
ruffle_web-wasm_extensions.js:1195 ERROR core/src/display_object/movie_clip.rs:4371 Got AVM2 error ReferenceError: Error #1065: Variable EditorAssets_NEW_QUEST_AVAILABLE is not defined. when attempting to assign symbol class com.gaiaonline.aquarium.model::EditorAssets_NEW_QUEST_AVAILABLE`

### Expected behavior

With 2024-06-21 build, the game would start without major issues and is playable.

### Content Location

Game can be accessed at 

https://www.gaiaonline.com/aquarium

Though user registration is required.

### Affected platform

Browser's extension

### Operating system

MacOS Sonoma

### Browser

Chrome

### Additional information

Happens to all users regardless of OS and browsers.

**Comment by torokati44** [comment]
Based on the dates, this probably regressed with https://github.com/ruffle-rs/ruffle/pull/16747 (@Aaron1011).

**Comment by Aaron1011** [comment]
This should be fixed by https://github.com/ruffle-rs/ruffle/pull/16853

**Comment by lanzer-gaia** [comment]
Aquarium working once again with the latest build.  Thank you!
