### ISSUE TITLE
New versions of Ruffle (0.6.0 and a few nightly builds have an issue with rendering the player in Mission in Snowdrift

### ISSUE THREAD

**Issue by Sebby-Webby18250** [ruffle-rs/ruffle#24679]
### Describe the bug

The player does not show up on the game on both js and extension, here are the console logs:
content.js:555 Unable to check top-level optout: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://www.gstatic.com" from accessing a cross-origin frame.
checkPageOptout @ content.js:555
content.js:555 Unable to check top-level optout: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://shakwarehousecdn.vercel.app" from accessing a cross-origin frame.
checkPageOptout @ content.js:555
655.js:2262 INFO web/src/lib.rs:1416 Ruffle WASM module has been initialized
655.js:3718 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://developer.chrome.com/blog/autoplay/#web_audio
(anonymous) @ 655.js:3718
655.js:3718 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://developer.chrome.com/blog/autoplay/#web_audio
(anonymous) @ 655.js:3718
ruffle.js:5331 New Ruffle instance created (Version: 0.6.0 | WebAssembly extensions: ON | Used renderer: wgpu-webgl)
ruffle.js:5513 Loading SWF file misnowdriftland_final.swf
655.js:2262 ERROR core/src/library.rs:250 Tried to instantiate a non-registered character FocusManager
655.js:2262 ERROR core/src/library.rs:250 Tried to instantiate a non-registered character FocusManager

<img width="931" height="601" alt="Image" src="https://github.com/user-attachments/assets/d5155f5f-eba6-479c-8294-e6fb9bcbaa33" />

### Expected behavior

It works on the 0.2.0-nightly.2025.9.17

<img width="1019" height="718" alt="Image" src="https://github.com/user-attachments/assets/0bb01116-901f-49fa-821f-5c339ad7dc2d" />

### Content Location

The content in question is https://sites.google.com/view/sebshak/games/mission-in-snowdriftland or https://shakwarehousecdn.vercel.app/missioninsnowdriftland/index.html

### Affected platform

Browser's extension

### Operating system

Windows 11 Home

### Browser

Google Chrome 152.0.7977.83 (Official Build) (64-bit) (cohort: Stable)

**Comment by Lord-McSweeney** [comment]
There are some more warnings and errors logged:
```
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'actor'
WARN ruffle_core::avm1::activation: Cannot enumerate Undefined
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 't2_b'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 't2_b'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr2'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_t'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_t_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_b1_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_ek'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 't2_b'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr2'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_is1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_t_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_b1_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_ek'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'bh'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 't2_b'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr2'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_is1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_t_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_b1_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_ek'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'bh'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 't2_b'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr2'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_kr1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_is1'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_t_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_b1_l'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'd_ek'
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'bh'
RROR ruffle_core::library: Tried to instantiate a non-registered character s_c_t_l
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_t_l'
RROR ruffle_core::library: Tried to instantiate a non-registered character s_c_b1_l
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_c_b1_l'
RROR ruffle_core::library: Tried to instantiate a non-registered character s_b_s
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
RROR ruffle_core::library: Tried to instantiate a non-registered character s_b_s
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
RROR ruffle_core::library: Tried to instantiate a non-registered character s_b_s
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 's_b_s'
RROR ruffle_core::library: Tried to instantiate a non-registered character bh
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'bh'
RROR ruffle_core::library: Tried to instantiate a non-registered character bh
WARN ruffle_core::avm1::globals::movie_clip: Unable to attach 'bh'
```

**Comment by Sebby-Webby18250** [comment]
I belive that you have to refresh multiple times if you have to clear the cache of the website
