### ISSUE TITLE
Fishao game can't get past loading screen

### ISSUE THREAD

**Issue by michiel2005** [ruffle-rs/ruffle#10531]
### Describe the bug

The game fishao does not get past the loading screen.

You can register here:  It is possible with a guest account so you don't have to give any email, username or password.
https://www.fishao.com
This is the link were the game starts from:
https://www.fishao.com/play

I think that there needs to be loaded a new swf file in the browser but that's not being done.

### Expected behavior

I expect the game to load.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Brave

**Comment by michiel2005** [comment]
It is a avm 2 game, I can't add that label myself.

**Comment by n0samu** [comment]
The error is:
`ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0xdae2c10 }) to handler FunctionObject(FunctionObject { ptr: 0xac0460 }) : ReferenceError: Error #1069: Property close not found on com.ax3.net.URLLoaderRepeatable and there is no default value.	at com.ax3.net::BinaryLoaderRepeatable/destroyUrlLoader()	at com.ax3.net::BinaryLoaderRepeatable/onLoadComplete()`

**Comment by Lord-McSweeney** [comment]
`URLLoader.close` has since been stubbed, so the game now hits a script timeout execution while loading. After bumping the max timeout to 60 seconds, I managed to get into this screen: 
![www fishao com_play](https://github.com/ruffle-rs/ruffle/assets/84632019/7bd48b14-f2b1-4d65-bc5c-d6bc0abb7325)

From here the game needs `Socket`.

**Comment by michiel2005** [comment]
Great Flash's greatest game is beginning to work😅. 
As you can see, the light blue parts should be a more blue colour, this is due to unimplemented filter effects I think #15.

**Comment by michiel2005** [comment]
Closing this issue because the game is not available anymore.
