### PR TITLE
core: Perform construction of objects on frame targeted by queued goto in SWFv9

### LINKED ISSUE #22677: Regression: Wedding Trouble - Cannot access a property or method of a null object reference
### Describe the bug

I can not select the level. Looks like the regression started with https://github.com/ruffle-rs/ruffle/pull/22408

```
ERROR core/src/display_object/movie_clip.rs:2389 Error occurred when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference.
at rutch.theStage::TheStage/frame41()
```

### Expected behavior

Select the level

### Content Location

PLAY Online - https://www.gameflare.com/online-game/wedding-trouble/
SWF URL  - https://data.gameflare.com/games/820/9DN05aTvnlcb9e.swf

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome

### Additional information

_No response_

### LINKED ISSUE #22997: Regression: Shop Empire 2 - Error dispatching event "enterSomeFrame"
### Describe the bug

After entering my name, I want to start the game, but there is just a white screen. Looks like another regression started with https://github.com/ruffle-rs/ruffle/pull/22408
```
ERROR core/src/avm2.rs:688 Error dispatching event "enterSomeFrame": TypeError: Error #1009: Cannot access a property or method of a null object reference.
at ShopEmpire2_fla::MainProgram_64/checkFrame()
at flash.events::EventDispatcher/dispatchEventInternal()
at flash.events::EventDispatcher/dispatchEvent()
at ShopEmpire2_fla::MainProgram_64/frame2()
```

### Expected behavior

Run the first level

### Content Location

PLAY Online - https://www.gameflare.com/online-game/shop-empire-2/
SWF URL - https://data.gameflare.com/games/2892/Mtia6vHMFbAR6E.swf

SWF Version: 9

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

_No response_

### Additional information

_No response_

### LINKED ISSUE #23063: Regression: Homestuck Pogo Ride - timeline object is incorrectly null when using goto in SWFv9
### Describe the bug

When the "Giddy Up!" button is clicked, nothing happens.

### Expected behavior

When clicked, the button should be replaced by a 30-second timer and a minigame starts.

### Content Location

https://mrcheeze.github.io/homestuck-ruffle-tester/#00476
https://mrcheeze.github.io/homestuck-ruffle-tester/flash/00476.swf

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla Firefox

### Additional information

This worked before commit https://github.com/ruffle-rs/ruffle/commit/ce6e7c828efbd4ec05817d4952e763fae0cd633b from https://github.com/ruffle-rs/ruffle/pull/22408 .

In only the versions where it is broken, this error is logged:
```
2026-02-18T03:44:13.709097Z ERROR ruffle_core::display_object::movie_clip: Error occurred when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference.
        at ride_fla::MainTimeline/frame2()
```

### LINKED ISSUE #23125: Ace Gangster START button doesnt not work
### Describe the bug

when i load the game on the froyogames.com logo the start button does nothing

### Expected behavior

i expected the game to work when i click start

### Content Location

[AceGangster.swf.zip](https://github.com/user-attachments/files/25562793/AceGangster.swf.zip)

### Affected platform

Desktop app

### Operating system

Flatpak (linux), Web

### Browser

Firefox 148.0 (64-bit)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Fixes #22677, fixes #22997, fixes #23063, fixes #23125, fixes Road of the Dead

As `run_inner_goto_frame` is a no-op on SWFv9, such objects were not being constructed at the correct time. This PR fixes that.

This should also fix ​#22820 but I haven't been able to test it

### CODE REVIEW

**Comment by MartySVK** [comment]
fixes also https://github.com/ruffle-rs/ruffle/issues/23125
