### ISSUE TITLE
Regression: Wedding Trouble - Cannot access a property or method of a null object reference

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#22677]
### Describe the bug

I can not select the level. Looks like the regression started with https://github.com/ruffle-rs/ruffle/pull/22408

```
ERROR core/src/display_object/movie_clip.rs:2389 Error occurred when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference.
at rutch.theStage::TheStage/frame41()
```

### Expected behavior

Select the level

### Content Location

PLAY Online - https://www.gameflare.com/online-game/wedding-trouble/
SWF URL  - https://data.gameflare.com/games/820/9DN05aTvnlcb9e.swf

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome
