### ISSUE TITLE
Error playing a flash game

### ISSUE THREAD

**Issue by tabaqo** [ruffle-rs/ruffle#1630]
Ruffle gives an error message when trying to play this game http://www.digyourowngrave.com/spot-the-difference/

**Comment by parkerlreed** [comment]
You can click view error details and copy and paste the text

Here it is for this game in the web player

```
# Error Info
Error name: TypeError
Error message: ai[e] is not a function
Error stack:
```
TypeError: ai[e] is not a function
    at Function.di (chrome-extension://eokbmhhhibllgejninhfladoonkogkli/dist/ruffle.js:1:28225)
    at http://www.digyourowngrave.com/javascripts/prototype.js:214:23
    at async chrome-extension://eokbmhhhibllgejninhfladoonkogkli/dist/ruffle.js:1:1349
    at async HTMLElement.ensure_fresh_instance (chrome-extension://eokbmhhhibllgejninhfladoonkogkli/dist/ruffle.js:1:13584)
    at async HTMLElement.stream_swf_url (chrome-extension://eokbmhhhibllgejninhfladoonkogkli/dist/ruffle.js:1:14922)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.digyourowngrave.com/spot-the-difference/

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
```

**Comment by Toad06** [comment]
Hmm, it's the same issue as #1507 (the game works in nightly builds <= 2020-10-16).
Need to investigate that.

**Comment by Toad06** [comment]
I've run a bisect and it does appear the issue was introduced in commit 990052db77601f792f2867554a5f49c2c793bcfd.

**Comment by Toad06** [comment]
Fixed by #2051.
