### ISSUE TITLE
Regression? - Fishdom - Goes black throws GameFont error

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#12961]
### Describe the bug

This game worked fine before but now some errors appear and the game goes black after the loading screen. Dunno what caused it but must have been with the latest built since around 1 week.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/fishdom.swf
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character MGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character CGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character YGameFont
ruffle_web-wasm_extensions.js:719 ERROR core/src/library.rs:213 Tried to instantiate non-registered character YGameFont
ruffle_web-wasm_extensions.js:719

### Expected behavior

Run again

### Affected platform

Desktop app

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
This is yet another regression caused by 771f5685093cc668e48c097b67e124dda7788f9a. @CUB3D, pinging you as the author of the commit.
